#include QMK_KEYBOARD_H

// tapdance keycodes
enum td_keycodes {
  L_PRN_ABK, R_PRN_ABK, SUPER_ESC, SUPER_LOCK, SMART_CAPS
};
// define a type containing as many tapdance states as you need
typedef enum {
  SINGLE_TAP,
  SINGLE_HOLD,
  DOUBLE_SINGLE_TAP
} td_state_t;

// create a global instance of the tapdance state type
static td_state_t td_state;

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk-compile-json. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//////////////////////////////0//////////////////////////////
	[0] = LAYOUT_ergodox(
//=====================left=====================
   TD(SUPER_ESC),            KC_1,            KC_2,            KC_3,            KC_4,            KC_5,          KC_GRV,
  TD(SMART_CAPS),            KC_Q,            KC_W,            KC_E,            KC_R,            KC_T,         KC_LBRC,
          KC_TAB,            KC_A,            KC_S,            KC_D,            KC_F,            KC_G,
         KC_LSFT,            KC_Z,            KC_X,            KC_C,            KC_V,            KC_B,   TD(L_PRN_ABK),
         KC_LCTL,         KC_LGUI,         KC_LALT,         KC_MINS,          KC_EQL,
                                                                                               KC_INS,         KC_PSCR,
                                                                                                                KC_DEL,
                                                                      LCTL_T(KC_SPC), LGUI_T(KC_BSPC),    LT(2,KC_ENT),

//=====================right=====================
          KC_APP,            KC_6,            KC_7,            KC_8,            KC_9,            KC_0,  TD(SUPER_LOCK),
         KC_RBRC,            KC_Y,            KC_U,            KC_I,            KC_O,            KC_P,         KC_BSLS,
                             KC_H,            KC_J,            KC_K,            KC_L,         KC_SCLN,         KC_QUOT,
   TD(R_PRN_ABK),            KC_N,            KC_M,         KC_COMM,          KC_DOT,         KC_SLSH,         KC_RSFT,
                                           KC_LEFT,         KC_DOWN,           KC_UP,         KC_RGHT,         KC_RCTL,
         KC_HOME,          KC_END,
           TT(2),
    LT(2,KC_ESC),         KC_BSPC,    LT(1,KC_ENT)
),
//////////////////////////////1//////////////////////////////
	[1] = LAYOUT_ergodox(
//=====================left=====================
         _______,           KC_F1,           KC_F2,           KC_F3,           KC_F4,           KC_F5,          KC_F11,
         _______,         KC_WH_U,         KC_BTN1,         KC_MS_U,         KC_BTN2,         KC_WH_U,         _______,
         _______,         KC_WH_D,         KC_MS_L,         KC_MS_D,         KC_MS_R,         KC_WH_D,
         _______,           TG(3),         KC_BTN1,         KC_BTN3,         KC_BTN2,         XXXXXXX,         _______,
         _______,         _______,         _______,         _______,         _______,
                                                                                              _______,         _______,
                                                                                                               _______,
                                                                             _______,         _______,         _______,

//=====================right=====================
          KC_F12,           KC_F6,           KC_F7,           KC_F8,           KC_F9,          KC_F10,         _______,
         _______,         KC_PGUP,         KC_HOME,           KC_UP,          KC_END,         KC_PGUP,         _______,
                          KC_PGDN,         KC_LEFT,         KC_DOWN,         KC_RGHT,         KC_PGDN,         _______,
         _______,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         _______,
                                           _______,         _______,         _______,         _______,         _______,
         KC_WHOM,         KC_WREF,
         _______,
         _______,         _______,         _______
),
//////////////////////////////2//////////////////////////////
	[2] = LAYOUT_ergodox(
//=====================left=====================
         QK_BOOT,           KC_F1,           KC_F2,           KC_F3,           KC_F4,           KC_F5,          KC_F11,
         _______,         KC_WH_U,         KC_BTN1,         KC_MS_U,         KC_BTN2,         KC_WH_U,         _______,
         _______,         KC_WH_D,         KC_MS_L,         KC_MS_D,         KC_MS_R,         KC_WH_D,
         _______,           TG(3),         KC_BTN1,         KC_BTN3,         KC_BTN2,         XXXXXXX,         _______,
         _______,         _______,         _______,         _______,         _______,
                                                                                              KC_MYCM,         KC_CALC,
                                                                                                               _______,
                                                                             _______,         _______,         _______,

//=====================right=====================
          KC_F12,         XXXXXXX,          KC_NUM,         KC_PSLS,         KC_PAST,         KC_PMNS,         _______,
         _______,         KC_PGUP,            KC_7,            KC_8,            KC_9,         KC_PPLS,         _______,
                          KC_PGDN,            KC_4,            KC_5,            KC_6,         KC_PPLS,         _______,
         _______,         XXXXXXX,            KC_1,            KC_2,            KC_3,         KC_PENT,         _______,
                                           XXXXXXX,            KC_0,          KC_DOT,         KC_PENT,         _______,
         _______,         _______,
         _______,
         _______,         _______,         _______
),
//////////////////////////////3//////////////////////////////
	[3] = LAYOUT_ergodox(
//=====================left=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                                                                              XXXXXXX,         XXXXXXX,
                                                                                                               XXXXXXX,
                                                                             XXXXXXX,           MO(4),           MO(4),

//=====================right=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                          XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                           XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,
         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX
),
//////////////////////////////4//////////////////////////////
	[4] = LAYOUT_ergodox(
//=====================left=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,           TG(3),         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                                                                              XXXXXXX,         XXXXXXX,
                                                                                                               XXXXXXX,
                                                                             XXXXXXX,         XXXXXXX,         XXXXXXX,

//=====================right=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                          XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                           XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,
         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX
)
};



// Runs just one time when the keyboard initializes.
void matrix_init_user(void) {
};
unsigned int scan_timer = 0;
void reset_scan_timer(unsigned int v) {
  scan_timer = v;
}
// Runs constantly in the background, in a loop.
void matrix_scan_user(void) {
    uint8_t layer = biton32(layer_state);
    scan_timer++;
    ergodox_board_led_off();
    ergodox_right_led_1_off();
    ergodox_right_led_2_off();
    ergodox_right_led_3_off();
    switch (layer) {
      // TODO: Make this relevant to the ErgoDox EZ.
        case 1:
            ergodox_right_led_1_on();
            break;
        case 2:
            ergodox_right_led_2_on();
            break;
        case 3:
            if (scan_timer & (0x01<<9))
            {
                ergodox_right_led_1_on();
                ergodox_right_led_2_on();
                ergodox_right_led_3_on();
            }
            return;
        default:
            // none
            break;
    };
    if (host_keyboard_led_state().caps_lock)
    {
        ergodox_right_led_3_on();
    }
    if (is_caps_word_on() && (scan_timer & (0x01<<7)))
    {
        ergodox_right_led_3_on();
    }
};

void l_prn_abk_released (tap_dance_state_t *state, void *user_data) {
  if ((!state->interrupted) && (!state->finished)) {
    tap_code16(KC_LPRN);
  }
}
void l_prn_abk_finished (tap_dance_state_t *state, void *user_data) {
  if (state->pressed) {
    if (state->interrupted) {
      tap_code16(KC_LPRN);
    } else {
      tap_code16(KC_LABK);
    }
  }
}
void r_prn_abk_released (tap_dance_state_t *state, void *user_data) {
  if ((!state->interrupted) && (!state->finished)) {
    tap_code16(KC_RPRN);
  }
}
void r_prn_abk_finished (tap_dance_state_t *state, void *user_data) {
  if (state->pressed) {
    if (state->interrupted) {
      tap_code16(KC_RPRN);
    } else {
      tap_code16(KC_RABK);
    }
  }
}

// determine the tapdance state to return
int cur_dance (tap_dance_state_t *state) {
  if (state->count == 1) {
    if (state->interrupted || !state->pressed) { return SINGLE_TAP; }
    else { return SINGLE_HOLD; }
  }
  if (state->count == 2) { return DOUBLE_SINGLE_TAP; }
  else { return state->count; } // any number higher than the maximum state value you return above
}

void super_esc_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case SINGLE_TAP:
      tap_code16(KC_ESC);
      break;
    case SINGLE_HOLD:
      if (detected_host_os() == OS_MACOS) {
        tap_code16(LCTL(LSFT(KC_W)));
      } else {
        tap_code16(LALT(KC_F4));
      }
      reset_tap_dance(state);
      break;
    case DOUBLE_SINGLE_TAP:
      tap_code16(LCTL(KC_W));
  }
}

void super_lock_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case DOUBLE_SINGLE_TAP:
      layer_on(3);
    case SINGLE_TAP:
      if (detected_host_os() == OS_MACOS) {
        tap_code16(RCTL(RGUI(KC_Q)));
      } else {
        tap_code16(RGUI(KC_L));
      }
      break;
    case SINGLE_HOLD:
      register_code16(KC_SLEP);
      break;
  }
}

void super_lock_reset (tap_dance_state_t *state, void *user_data) {
  switch (td_state) {
    case DOUBLE_SINGLE_TAP:
    case SINGLE_TAP:
      break;
    case SINGLE_HOLD:
      unregister_code16(KC_SLEP);
      break;
  }
}

void smart_caps_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case SINGLE_TAP:
      if (host_keyboard_led_state().caps_lock) {
        tap_code16(KC_CAPS);
        caps_word_off();
      }
      else
      {
        reset_scan_timer(0x01<<7);
        caps_word_toggle();
      }
      break;
    case DOUBLE_SINGLE_TAP:
      if (is_caps_word_on())
      {
          caps_word_off();
      }
      tap_code16(KC_CAPS);
      break;
    case SINGLE_HOLD:
      break;
  }
}

// define `ACTION_TAP_DANCE_FN_ADVANCED()` for each tapdance keycode, passing in `finished` and `reset` functions
tap_dance_action_t tap_dance_actions[] = {
  [L_PRN_ABK] = ACTION_TAP_DANCE_FN_ADVANCED_WITH_RELEASE(NULL, l_prn_abk_released, l_prn_abk_finished, NULL),
  [R_PRN_ABK] = ACTION_TAP_DANCE_FN_ADVANCED_WITH_RELEASE(NULL, r_prn_abk_released, r_prn_abk_finished, NULL),
  [SUPER_ESC] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, super_esc_finished, NULL),
  [SUPER_LOCK] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, super_lock_finished, super_lock_reset),
  [SMART_CAPS] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, smart_caps_finished, NULL),
};

bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, with shift applied.
        case KC_A ... KC_Z:
        case KC_MINS:
            add_weak_mods(MOD_BIT(KC_LSFT));  // Apply shift to next key.
            return true;

        // Keycodes that continue Caps Word, without shifting.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_UNDS:
        case TD(SMART_CAPS):
        case KC_LCTL:
        case KC_LGUI:
        case KC_LALT:
        case KC_LSFT:
        case KC_RCTL:
        case KC_RGUI:
        case KC_RALT:
        case KC_RSFT:
            return true;

        default:
            return false;  // Deactivate Caps Word.
    }
}

bool process_detected_host_os_user(os_variant_t detected_os) {
  switch (detected_os) {
    case OS_WINDOWS:
      ergodox_right_led_1_on();
      break;
    case OS_LINUX:
      ergodox_right_led_2_on();
      break;
    case OS_MACOS:
      ergodox_right_led_3_on();
      break;
    case OS_UNSURE:
    case OS_IOS:
      ;
  }
  wait_ms(300);
  return true;
}
