#include QMK_KEYBOARD_H

// tapdance keycodes
enum td_keycodes {
  L_PRN_ABK, R_PRN_ABK, SUPER_ESC, SUPER_LOCK
};
// define a type containing as many tapdance states as you need
typedef enum {
  SINGLE_TAP,
  SINGLE_HOLD,
  DOUBLE_SINGLE_TAP
} td_state_t;

// create a global instance of the tapdance state type
static td_state_t td_state;

// declare your tapdance functions:

// function to determine the current tapdance state
int cur_dance (tap_dance_state_t *state);

// `finished` and `reset` functions for each tapdance keycode
void l_prn_abk_finished (tap_dance_state_t *state, void *user_data);
void r_prn_abk_reset (tap_dance_state_t *state, void *user_data);

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk-compile-json. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//////////////////////////////0//////////////////////////////
	[0] = LAYOUT_ergodox(
//=====================left=====================
   TD(SUPER_ESC),            KC_1,            KC_2,            KC_3,            KC_4,            KC_5,          KC_GRV,
         KC_CAPS,            KC_Q,            KC_W,            KC_E,            KC_R,            KC_T,         KC_LBRC,
          KC_TAB,            KC_A,            KC_S,            KC_D,            KC_F,            KC_G,
         KC_LSFT,            KC_Z,            KC_X,            KC_C,            KC_V,            KC_B,   TD(L_PRN_ABK),
         KC_LCTL,         KC_LGUI,         KC_LALT,         KC_MINS,          KC_EQL,
                                                                                               KC_INS,         KC_PSCR,
                                                                                                                KC_DEL,
                                                                      RCTL_T(KC_SPC), RGUI_T(KC_BSPC),    LT(2,KC_ENT),

//=====================right=====================
          KC_APP,            KC_6,            KC_7,            KC_8,            KC_9,            KC_0,  TD(SUPER_LOCK),
         KC_RBRC,            KC_Y,            KC_U,            KC_I,            KC_O,            KC_P,         KC_BSLS,
                             KC_H,            KC_J,            KC_K,            KC_L,         KC_SCLN,         KC_QUOT,
   TD(R_PRN_ABK),            KC_N,            KC_M,         KC_COMM,          KC_DOT,         KC_SLSH,         KC_RSFT,
                                           KC_LEFT,         KC_DOWN,           KC_UP,         KC_RGHT,         KC_RCTL,
         KC_HOME,          KC_END,
           TT(2),
    LT(2,KC_ESC),         KC_BSPC,    LT(1,KC_ENT)
),
//////////////////////////////1//////////////////////////////
	[1] = LAYOUT_ergodox(
//=====================left=====================
         _______,           KC_F1,           KC_F2,           KC_F3,           KC_F4,           KC_F5,          KC_F11,
         _______,         KC_WH_U,         KC_BTN1,         KC_MS_U,         KC_BTN2,         KC_WH_U,         _______,
         _______,         KC_WH_D,         KC_MS_L,         KC_MS_D,         KC_MS_R,         KC_WH_D,
         _______,           TG(3),         KC_BTN1,         KC_BTN3,         KC_BTN2,         XXXXXXX,         _______,
         _______,         _______,         _______,         _______,         _______,
                                                                                              _______,         _______,
                                                                                                               _______,
                                                                             _______,         _______,         _______,

//=====================right=====================
          KC_F12,           KC_F6,           KC_F7,           KC_F8,           KC_F9,          KC_F10,         _______,
         _______,         KC_PGUP,         KC_HOME,           KC_UP,          KC_END,         KC_PGUP,         _______,
                          KC_PGDN,         KC_LEFT,         KC_DOWN,         KC_RGHT,         KC_PGDN,         _______,
         _______,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         _______,
                                           _______,         _______,         _______,         _______,         _______,
         KC_WHOM,         KC_WREF,
         _______,
         _______,         _______,         _______
),
//////////////////////////////2//////////////////////////////
	[2] = LAYOUT_ergodox(
//=====================left=====================
         QK_BOOT,           KC_F1,           KC_F2,           KC_F3,           KC_F4,           KC_F5,          KC_F11,
         _______,         KC_WH_U,         KC_BTN1,         KC_MS_U,         KC_BTN2,         KC_WH_U,         _______,
         _______,         KC_WH_D,         KC_MS_L,         KC_MS_D,         KC_MS_R,         KC_WH_D,
         _______,           TG(3),         KC_BTN1,         KC_BTN3,         KC_BTN2,         XXXXXXX,         _______,
         _______,         _______,         _______,         _______,         _______,
                                                                                              KC_MYCM,         KC_CALC,
                                                                                                               _______,
                                                                             _______,         _______,         _______,

//=====================right=====================
          KC_F12,         XXXXXXX,          KC_NUM,         KC_PSLS,         KC_PAST,         KC_PMNS,         _______,
         _______,         KC_PGUP,            KC_7,            KC_8,            KC_9,         KC_PPLS,         _______,
                          KC_PGDN,            KC_4,            KC_5,            KC_6,         KC_PPLS,         _______,
         _______,         XXXXXXX,            KC_1,            KC_2,            KC_3,         KC_PENT,         _______,
                                           XXXXXXX,            KC_0,          KC_DOT,         KC_PENT,         _______,
         _______,         _______,
         _______,
         _______,         _______,         _______
),
//////////////////////////////3//////////////////////////////
	[3] = LAYOUT_ergodox(
//=====================left=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                                                                              XXXXXXX,         XXXXXXX,
                                                                                                               XXXXXXX,
                                                                             XXXXXXX,           MO(4),           MO(4),

//=====================right=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                          XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                           XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,
         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX
),
//////////////////////////////4//////////////////////////////
	[4] = LAYOUT_ergodox(
//=====================left=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,           TG(3),         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                                                                              XXXXXXX,         XXXXXXX,
                                                                                                               XXXXXXX,
                                                                             XXXXXXX,         XXXXXXX,         XXXXXXX,

//=====================right=====================
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                          XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
                                           XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,         XXXXXXX,
         XXXXXXX,         XXXXXXX,
         XXXXXXX,
         XXXXXXX,         XXXXXXX,         XXXXXXX
)
};



// Runs just one time when the keyboard initializes.
void matrix_init_user(void) {
};

// Runs constantly in the background, in a loop.
void matrix_scan_user(void) {
    static unsigned int timer = 0;
    uint8_t layer = biton32(layer_state);

    ergodox_board_led_off();
    ergodox_right_led_1_off();
    ergodox_right_led_2_off();
    ergodox_right_led_3_off();
    switch (layer) {
      // TODO: Make this relevant to the ErgoDox EZ.
        case 1:
            ergodox_right_led_1_on();
            break;
        case 2:
            ergodox_right_led_2_on();
            break;
        case 3:
            timer++;
            if (timer & (0x01<<9))
            {
                ergodox_right_led_1_on();
                ergodox_right_led_2_on();
                ergodox_right_led_3_on();
            }
            return;
        default:
            // none
            break;
    };
    if (host_keyboard_led_state().caps_lock)
    {
        ergodox_right_led_3_on();
    }
};

// determine the tapdance state to return
int cur_dance (tap_dance_state_t *state) {
  if (state->count == 1) {
    if (state->interrupted || !state->pressed) { return SINGLE_TAP; }
    else { return SINGLE_HOLD; }
  }
  if (state->count == 2) { return DOUBLE_SINGLE_TAP; }
  else { return 3; } // any number higher than the maximum state value you return above
}

// handle the possible states for each tapdance keycode you define:

void l_prn_abk_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case SINGLE_TAP:
      register_code16(KC_LPRN);
      break;
    case SINGLE_HOLD:
      register_code16(KC_LABK);
      reset_tap_dance(state);
      break;
    case DOUBLE_SINGLE_TAP: // allow nesting of 2 parens `((` within tapping term
      tap_code16(KC_LPRN);
      register_code16(KC_LPRN);
  }
}

void l_prn_abk_reset (tap_dance_state_t *state, void *user_data) {
  switch (td_state) {
    case SINGLE_TAP:
      wait_ms(10);
      unregister_code16(KC_LPRN);
      break;
    case SINGLE_HOLD:
      unregister_code16(KC_LABK);
      break;
    case DOUBLE_SINGLE_TAP:
      unregister_code16(KC_LPRN);
  }
}
void r_prn_abk_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case SINGLE_TAP:
      register_code16(KC_RPRN);
      break;
    case SINGLE_HOLD:
      register_code16(KC_RABK);
      reset_tap_dance(state);
      break;
    case DOUBLE_SINGLE_TAP: // allow nesting of 2 parens `((` within tapping term
      tap_code16(KC_RPRN);
      register_code16(KC_RPRN);
  }
}

void r_prn_abk_reset (tap_dance_state_t *state, void *user_data) {
  switch (td_state) {
    case SINGLE_TAP:
      wait_ms(10);
      unregister_code16(KC_RPRN);
      break;
    case SINGLE_HOLD:
      unregister_code16(KC_RABK);
      break;
    case DOUBLE_SINGLE_TAP:
      unregister_code16(KC_RPRN);
  }
}

void super_esc_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case SINGLE_TAP:
      register_code16(KC_ESC);
      break;
    case SINGLE_HOLD:
      if (detected_host_os() == OS_MACOS) {
        register_code16(LCTL(KC_Q));
      } else {
        register_code16(LALT(KC_F4));
      }
      reset_tap_dance(state);
      break;
    case DOUBLE_SINGLE_TAP:
      register_code16(LCTL(KC_W));
  }
}

void super_esc_reset (tap_dance_state_t *state, void *user_data) {
  switch (td_state) {
    case SINGLE_TAP:
      unregister_code16(KC_ESC);
      break;
    case SINGLE_HOLD:
      
      if (detected_host_os() == OS_MACOS) {
        unregister_code16(LCTL(KC_Q));
      } else {
        unregister_code16(LALT(KC_F4));
      }
      break;
    case DOUBLE_SINGLE_TAP:
      unregister_code16(LCTL(KC_W));
  }
}

void super_lock_finished (tap_dance_state_t *state, void *user_data) {
  td_state = cur_dance(state);
  switch (td_state) {
    case DOUBLE_SINGLE_TAP:
      layer_on(3);
    case SINGLE_TAP:
      if (detected_host_os() == OS_MACOS) {
        register_code16(RCTL(RGUI(KC_Q)));
      } else {
        register_code16(RGUI(KC_L));
      }
      break;
    case SINGLE_HOLD:
      register_code16(KC_SLEP);
      break;
  }
}

void super_lock_reset (tap_dance_state_t *state, void *user_data) {
  switch (td_state) {
    case DOUBLE_SINGLE_TAP:
    case SINGLE_TAP:
      if (detected_host_os() == OS_MACOS) {
        unregister_code16(RCTL(RGUI(KC_Q)));
      } else {
        unregister_code16(RGUI(KC_L));
      }
      break;
    case SINGLE_HOLD:
      unregister_code16(KC_SLEP);
      break;
  }
}
// define `ACTION_TAP_DANCE_FN_ADVANCED()` for each tapdance keycode, passing in `finished` and `reset` functions
tap_dance_action_t tap_dance_actions[] = {
  [L_PRN_ABK] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, l_prn_abk_finished, l_prn_abk_reset),
  [R_PRN_ABK] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, r_prn_abk_finished, r_prn_abk_reset),
  [SUPER_ESC] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, super_esc_finished, super_esc_reset),
  [SUPER_LOCK] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, super_lock_finished, super_lock_reset),
};

bool process_detected_host_os_user(os_variant_t detected_os) {
  switch (detected_os) {
    case OS_WINDOWS:
      ergodox_right_led_1_on();
      break;
    case OS_LINUX:
      ergodox_right_led_2_on();
      break;
    case OS_MACOS:
      ergodox_right_led_3_on();
      break;
    case OS_UNSURE:
    case OS_IOS:
      ;
  }
  wait_ms(300);
  return true;
}
